/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.davidasensio.algorithms

import kotlin.test.Test

class AlgorithmTest {

    @Test
    fun testCountdown() {
        Alg03Recursion.runCountdownRecursively(90)
    }

    @Test
    fun testTailrecCountdown() {
        Alg03Recursion.runTailrecCountdownRecursively(20000)
    }

    @Test
    fun testFactorial() {
        Alg03Recursion.runFactorialRecursively(10)
    }

    @Test
    fun testTailrecFactorial() {
        Alg03Recursion.runTailrecFactorialRecursively(5)
    }

    @Test
    fun testSelectionsort() {
        Alg02SelectionSort.runSelectionSort((1 .. 1000).toList().shuffled())
    }

    @Test
    fun testQuicksort() {
        Alg04Quicksort.runQuicksort((1 .. 10).toList().shuffled())
    }

    @Test
    fun testBreadthFirstSearch() {
        Alg06BreadthFirstSearch.runBreadthFirstSearch()
    }

}
